export type Language = 'en' | 'ar';

export const translations = {
  en: {
    appName: "ATS AI CV Build",
    edit: "Edit",
    preview: "Preview",
    exportPdf: "Print",
    downloadPdf: "Download PDF",
    fillSampleData: "Fill with Example Data",
    livePreview: "Live Preview",
    atsFormat: "Standard ATS-friendly format. Use 'Save as PDF' in the print dialog for best results.",
    autoSaving: "Auto-saving",
    quickStats: "Quick Stats",
    totalResumes: "Total Resumes",
    atsScore: "ATS Score",
    jobTracker: "Job Application Tracker",
    companyName: "Company Name",
    jobStatus: "Status",
    appliedDate: "Applied Date",
    addJob: "Add Job",
    statusApplied: "Applied",
    statusInterview: "Interview",
    statusAccepted: "Accepted",
    statusRejected: "Rejected",
    lastUpdated: "Last Updated",
    skillGapAnalysis: "Skill Gap Analysis",
    yourSkills: "Your Skills",
    marketDemand: "Market Demand",
    missingSkills: "Top Missing Skills",
    aiCareerTips: "Smart Career Tips",
    tip1: "Use strong action verbs like 'Led', 'Developed', and 'Optimized'.",
    tip2: "Quantify your achievements with numbers and percentages.",
    tip3: "Ensure your LinkedIn profile is up to date and matches your CV.",
    tip4: "Keep your CV to 1-2 pages maximum for better readability.",
    tip5: "Ensure your resume is machine-readable by avoiding complex layouts.",
    personalInfo: "Personal Information",
    fullName: "Full Name",
    fullNamePlaceholder: "e.g., John Doe",
    jobTitle: "Target Job Title",
    jobTitlePlaceholder: "e.g., Software Engineer",
    email: "Email",
    emailPlaceholder: "e.g., john@example.com",
    phone: "Phone",
    phonePlaceholder: "e.g., +1 234 567 890",
    location: "Location",
    locationPlaceholder: "e.g., New York, NY",
    linkedin: "LinkedIn",
    linkedinPlaceholder: "e.g., linkedin.com/in/johndoe",
    summary: "Professional Summary",
    summaryPlaceholder: "Briefly describe your professional background and key achievements...",
    experience: "Experience",
    company: "Company",
    position: "Position",
    startDate: "Start Date",
    endDate: "End Date",
    datePlaceholder: "MM/YYYY",
    present: "Present",
    expPlaceholder: "Key achievements (use bullet points)...",
    education: "Education",
    school: "School",
    degree: "Degree",
    gradDate: "Graduation Date",
    skills: "Skills",
    skillsPlaceholder: "Build, TypeScript, Node.js...",
    aiModalTitle: "AI ATS Optimization",
    aiModalSubtitle: "Paste the job description to tailor your CV.",
    jobDescPlaceholder: "Paste the job description here...",
    cancel: "Cancel",
    optimizeNow: "Optimize Now",
    optimizing: "Optimizing...",
    optComplete: "Optimization Complete!",
    optCompleteSub: "Your CV has been tailored for the job.",
    technicalSoftSkills: "Technical & Soft Skills",
    training: "Training / Courses",
    certifications: "Certifications",
    requiredField: "This field is required",
    validationError: "Please fill in all required contact information (Email, Phone, Address, and Job Title).",
    settings: "Settings",
    language: "Language",
    languageWarning: "Note: The UI is in Arabic, but we recommend writing your resume in English for maximum ATS compatibility.",
    tipBanner: "ATS Tip: Use standard fonts and avoid complex layouts. Our builder ensures your CV is machine-readable.",
    tipQuantify: "ATS Tip: Quantify your results! Use numbers and percentages (e.g., 'Increased sales by 20%') to stand out.",
    tipTraining: "ATS Tip: Include relevant coursework that matches the job description keywords. Mention the platform or institution (e.g., Coursera, Udemy).",
    tipCert: "ATS Tip: Use the full name of the certification followed by the acronym in parentheses (e.g., Project Management Professional (PMP)).",
    tipSummary: "ATS Tip: Keep your summary concise (3-5 sentences). Include your most relevant job titles and top 2-3 skills.",
    tipExperience: "ATS Tip: Use bullet points for your responsibilities. Start each bullet with a strong action verb (e.g., 'Led', 'Developed').",
    targetJobDesc: "Target Job Description",
    pasteJD: "Paste the JD here to optimize for 100% ATS matching",
    jdPlaceholder: "Paste the job description for the role you are applying for...",
    basicContactInfo: "Basic contact information",
    careerOverview: "A brief overview of your career path",
    historyAchievements: "Your professional history and achievements",
    addExperience: "Add Experience",
    academicQualifications: "Your academic qualifications",
    addEducation: "Add Education",
    techSoftSkills: "Technical and soft skills",
    trainingWorkshops: "Training courses and workshops",
    addTraining: "Add Training",
    courseTitle: "Course Title",
    description: "Description",
    provider: "Provider",
    profAccreditedCerts: "Professional & Accredited Certifications",
    addCertification: "Add Certification",
    certTitle: "Certification Title",
    issuingOrg: "Issuing Organization",
    quantifyNumbers: "Use Numbers to Quantify",
    atsOptimizationTip: "ATS Optimization Tip",
    tipSkills: "ATS Tip: Include both technical skills (e.g., 'Python') and soft skills. Ensure the skills you list match the requirements mentioned in the job description.",
    done: "Done",
    faq: "FAQ",
    faqTitle: "Frequently Asked Questions",
    faqLangTitle: "Why must I write in English?",
    faqLangAnswer: "Most global companies and ATS systems are optimized for English. Writing in English increases your chances of being correctly parsed and noticed by international recruiters.",
    faqPdfTitle: "How do I save as PDF?",
    faqPdfAnswer: "Click the 'Export PDF' button. In the print window that opens, select 'Save as PDF' as the destination. This ensures the best formatting and machine-readability.",
    faqFreeTitle: "Is this website free?",
    faqFreeAnswer: "Yes, it is completely free to use.",
    faqImagesTitle: "Can I use images or icons?",
    faqImagesAnswer: "It is not recommended. ATS systems often struggle to read images, icons, or complex graphics. Our builder uses a clean, text-based layout to ensure maximum compatibility.",
    faqLengthTitle: "How long should my resume be?",
    faqLengthAnswer: "For most professionals, 1-2 pages is ideal. Focus on quality over quantity and ensure every point is relevant to the job you are applying for.",
    faqSecurityTitle: "Is my data secure?",
    faqSecurityAnswer: "We adhere to the highest privacy standards. Your data is not shared with any third party and is used solely to generate your personal CV.",
    faqAccountTitle: "Do I need an account?",
    faqAccountAnswer: "No, you don't need to create an account or log in. You can start building your CV immediately and all your data is saved locally in your browser.",
    faqMobileTitle: "Can I use it on mobile?",
    faqMobileAnswer: "Yes, our website is fully responsive and works perfectly on smartphones and tablets.",
    faqSupportTitle: "How can I get support?",
    faqSupportAnswer: "You can contact us at atsaicvbuild@gmail.com for support.",
    faqMultipleTitle: "Can I create multiple resumes?",
    faqMultipleAnswer: "Yes, you can create as many resumes as you need. Each one can be tailored to a specific job description.",
    faqColorsTitle: "Can I use colors in my CV?",
    faqColorsAnswer: "While subtle colors are okay, we recommend sticking to a clean black-and-white layout for maximum ATS compatibility. Our builder uses a professional, high-contrast design that is safe for all systems.",
    faqFontsTitle: "Which fonts are best for ATS?",
    faqFontsAnswer: "Standard, clean fonts like Arial, Calibri, and Helvetica are best. Our builder automatically uses ATS-friendly fonts to ensure your CV is parsed correctly.",
    faqGapsTitle: "How should I handle career gaps?",
    faqGapsAnswer: "Focus on the skills you gained during that time, such as freelance work, courses, or personal projects. Use our AI tool to highlight these strengths in your professional summary.",
    faqUploadTitle: "Can I upload my existing CV?",
    faqUploadAnswer: "Currently, you need to enter your information manually. This ensures that the data is structured perfectly for ATS systems and allows our AI to optimize every section effectively.",
    faqPrintTitle: "Which browser is best for printing?",
    faqPrintAnswer: "We recommend using Google Chrome or Microsoft Edge. When printing, ensure 'Headers and Footers' are unchecked and 'Background Graphics' are checked for the best visual result.",
    faqLimitTitle: "Is there a limit to AI optimizations?",
    faqLimitAnswer: "No, there is no limit! You can use the AI optimization tool as many times as you like for different job descriptions to ensure the best possible match.",
    faqUpdateTitle: "How do I update my CV later?",
    faqUpdateAnswer: "Simply return to the site. Since your data is saved in your browser's local storage, your information will be there waiting for you to make any updates.",
    faqSectionsTitle: "Can I add more sections?",
    faqSectionsAnswer: "Our builder focuses on the core sections required for ATS success. However, you can use the 'Experience' or 'Training' sections to include other relevant professional activities.",
    faqSkillsTitle: "What is the best way to list skills?",
    faqSkillsAnswer: "Group your skills by category (e.g., Programming Languages, Tools, Soft Skills) and ensure they match the keywords in the job description.",
    faqBrowserTitle: "Is my data saved if I close the browser?",
    faqBrowserAnswer: "Yes! We use your browser's local storage to keep your progress. As long as you don't clear your browser data, your CV will be available when you return.",
    faqAnyJobTitle: "Can I use this for any job?",
    faqAnyJobAnswer: "Yes! Our tool is designed to help you tailor your CV to any job description across various industries.",
    faqFreshGradTitle: "What if I'm a fresh graduate?",
    faqFreshGradAnswer: "Focus on your education, academic projects, internships, and relevant skills. Highlight your potential and how your academic background fits the role.",
    faqPhotoTitle: "Should I include a photo?",
    faqPhotoAnswer: "We recommend against it. Many ATS systems cannot process images, and in many regions, including a photo is discouraged to avoid unconscious bias in the hiring process.",
    faqCvResumeTitle: "What is the difference between a CV and a Resume?",
    faqCvResumeAnswer: "A CV is typically a detailed document covering your entire career and academic history, while a resume is a concise summary tailored to a specific job. Our builder helps you create a high-impact resume.",
    faqReferencesTitle: "How should I handle references?",
    faqReferencesAnswer: "It's standard practice to leave references off your resume. You can provide them separately if requested by the employer. This saves valuable space for your achievements.",
    faqTemplateTitle: "Can I change the template?",
    faqTemplateAnswer: "We provide one highly-optimized, ATS-friendly layout. This ensures that your resume is always professional and machine-readable, which is the most important factor for success.",
    faqCertsTitle: "How do I handle certifications?",
    faqCertsAnswer: "List the full name of the certification followed by the acronym in parentheses (e.g., Project Management Professional (PMP)). Include the issuing organization and the date you received it.",
    faqAddressTitle: "Should I include my address?",
    faqAddressAnswer: "In modern resumes, you only need to include your City and State/Country. A full street address is no longer necessary and can even be a privacy concern.",
    faqTechSkillsTitle: "What is the best way to list technical skills?",
    faqTechSkillsAnswer: "Group them by category (e.g., Programming Languages, Frameworks, Tools). This makes it easier for both the ATS and the recruiter to scan your expertise.",
    faqSoftSkillsTitle: "How do I handle soft skills?",
    faqSoftSkillsAnswer: "Instead of just listing them, try to demonstrate them in your experience section. For example, instead of saying 'Team Player', describe a project where you collaborated with others to achieve a goal.",
    faqAcademicTitle: "Can I use this for academic applications?",
    faqAcademicAnswer: "While our builder is optimized for professional resumes, you can certainly use it for academic roles. Focus on your research, publications, and teaching experience in the relevant sections.",
    faqFreelanceTitle: "How do I handle freelance work?",
    faqFreelanceAnswer: "Treat it like any other job. List 'Freelance' as the company and describe the projects you worked on and the results you achieved for your clients.",
    contactTitle: "Contact Us",
    contactSub: "Have a question? Send us a message and we'll get back to you via email.",
    contactName: "Name",
    contactEmail: "Email",
    contactSubject: "Subject",
    contactMessage: "Message",
    contactSend: "Send Message",
    contactSuccess: "Message sent successfully!",
    contactSuccessSub: "We will get back to you via email shortly.",
    contactError: "Failed to send message. Please try again.",
    contactEmailLabel: "Contact: atsaicvbuild@gmail.com",
    contactSubjectOptions: [
      "General Inquiry",
      "Technical Support",
      "Feature Request",
      "Bug Report",
      "Partnership",
      "Other"
    ],
    adminTitle: "Admin Messages",
    adminNoMessages: "No messages found.",
    adminSecret: "Admin Secret",
    adminLogin: "Login",
    adminWrongSecret: "Incorrect secret. Access denied.",
    adminReply: "Reply via Email",
    adminDrafting: "Drafting...",
    adminCopied: "Copied!",
    adminCopy: "Copy Draft",
    adminDelete: "Delete Message",
    adminMarkReplied: "Mark as Replied",
    adminReplied: "Replied",
    adminConfirmDelete: "Are you sure you want to delete this message?",
    termsTitle: "Terms of Use",
    termsAcceptance: "By using ATS AI CV Build, you agree to these terms.",
    termsUsage: "Usage: This tool is for personal use to create resumes. You are responsible for the content you enter.",
    termsPrivacy: "Privacy: Your data is stored locally in your browser. We do not store your personal resume data on our servers.",
    termsDisclaimer: "Disclaimer: We are not responsible for any employment outcomes or errors in the generated documents.",
    termsAts: "ATS Compatibility: While we provide an ATS-friendly template, compatibility depends on the content you provide. We recommend writing in English for best results.",
    termsAcceptanceTitle: "1. Acceptance of Terms",
    termsAcceptanceDesc: "By accessing and using ATS AI CV Build, you accept and agree to be bound by the terms and provision of this agreement.",
    termsEligibilityTitle: "2. Eligibility",
    termsEligibilityDesc: "You must be at least 13 years of age to use this service. By using the service, you represent and warrant that you meet this requirement.",
    termsLicenseTitle: "3. License to Use",
    termsLicenseDesc: "We grant you a personal, non-exclusive, non-transferable license to use the software for creating your personal resume.",
    termsProhibitedTitle: "4. Prohibited Activities",
    termsProhibitedDesc: "You agree not to use the service for any unlawful purpose or to solicit others to perform or participate in any unlawful acts.",
    termsContentTitle: "5. User Content Responsibility",
    termsContentDesc: "You are solely responsible for the accuracy and legality of the content you enter into your resume.",
    termsStorageTitle: "6. Data Storage",
    termsStorageDesc: "Your data is stored locally in your browser's local storage. We do not have access to your personal resume data unless you explicitly share it.",
    termsPrivacyTitle: "7. Privacy",
    termsPrivacyDesc: "We value your privacy. Please refer to our Privacy Policy section for details on how we handle non-personal data.",
    termsAtsTitle: "9. ATS Performance",
    termsAtsDesc: "While our templates are optimized for ATS, we cannot guarantee 100% parsing success for every single system in existence.",
    termsAvailabilityTitle: "10. System Availability",
    termsAvailabilityDesc: "We strive to keep the service available 24/7 but do not guarantee uninterrupted access due to maintenance or technical issues.",
    termsIpTitle: "11. Intellectual Property",
    termsIpDesc: "The software, design, and branding are the intellectual property of ATS AI CV Build.",
    termsThirdPartyTitle: "12. Third-Party Services",
    termsThirdPartyDesc: "Our service may contain links to third-party websites or services that are not owned or controlled by us.",
    termsNoGuaranteeTitle: "13. No Guarantee of Employment",
    termsNoGuaranteeDesc: "Using this tool does not guarantee that you will be hired or receive job interviews.",
    termsLiabilityTitle: "14. Limitation of Liability",
    termsLiabilityDesc: "In no event shall we be liable for any indirect, incidental, special, consequential or punitive damages.",
    termsIndemnityTitle: "15. Indemnification",
    termsIndemnityDesc: "You agree to indemnify and hold us harmless from any demands, loss, liability, claims or expenses made against us by any third party.",
    termsModificationsTitle: "17. Modifications to Terms",
    termsModificationsDesc: "We reserve the right to modify these terms at any time. Your continued use of the service constitutes acceptance of new terms.",
    termsAccountsTitle: "8. User Accounts (Optional)",
    termsAccountsDesc: "If you choose to save your data, you are responsible for maintaining the confidentiality of your local session and any shared links.",
    termsLawTitle: "16. Governing Law",
    termsLawDesc: "These terms shall be governed and construed in accordance with the laws of the jurisdiction in which the service operates, without regard to its conflict of law provisions.",
    termsFeedbackTitle: "26. Feedback and Suggestions",
    termsFeedbackDesc: "Any feedback or suggestions you provide shall be deemed non-confidential and we shall be free to use such information on an unrestricted basis.",
    termsAgreementTitle: "27. Entire Agreement",
    termsAgreementDesc: "These Terms constitute the entire agreement between us regarding our Service, and supersede any prior agreements we might have had between us regarding the Service.",
    termsContactTitle: "18. Contact Information",
    termsContactDesc: "If you have any questions about these Terms, please contact us at atsaicvbuild@gmail.com.",
    termsConductTitle: "19. User Conduct",
    termsConductDesc: "You agree not to use the service to create fraudulent documents, impersonate others, or engage in any activity that disrupts the service.",
    termsTerminationTitle: "20. Termination",
    termsTerminationDesc: "We reserve the right to terminate or suspend access to our service immediately, without prior notice, for conduct that we believe violates these Terms or is harmful to other users.",
    termsCookiesTitle: "21. Cookies & Local Storage",
    termsCookiesDesc: "We use browser local storage and essential cookies to save your resume data and preferences. By using the site, you consent to this storage.",
    termsUpdatesTitle: "22. Service Updates",
    termsUpdatesDesc: "We may update, modify, or discontinue features of the service at any time to improve security, performance, or user experience.",
    termsNoWarrantyTitle: "23. No Warranty",
    termsNoWarrantyDesc: "The service is provided on an 'as is' and 'as available' basis without any warranties of any kind, whether express or implied.",
    termsDataAccuracyTitle: "24. Data Accuracy",
    termsDataAccuracyDesc: "You are responsible for ensuring that all information provided in your resume is accurate and truthful.",
    termsSupportTitle: "25. Support Policy",
    termsSupportDesc: "While we strive to provide support via email, we do not guarantee a specific response time for inquiries.",
    privacyTitle: "Privacy Policy",
    privacyIntro: "Your privacy is important to us. This policy explains how we handle your data.",
    privacyDataCollectionTitle: "1. Data Collection",
    privacyDataCollectionDesc: "We do not collect or store your personal resume data on our servers. All information you enter is stored locally in your browser's local storage.",
    privacyCookiesTitle: "2. Cookies and Local Storage",
    privacyCookiesDesc: "We use local storage to save your progress and essential cookies for site functionality and security.",
    privacySecurityTitle: "3. Data Security",
    privacySecurityDesc: "While your data stays on your device, we implement industry-standard security measures on our server to protect the integrity of the service.",
    privacyUpdatesTitle: "4. Changes to This Policy",
    privacyUpdatesDesc: "We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.",
    privacyContactTitle: "5. Contact Us",
    privacyContactDesc: "If you have questions about your privacy, contact us at atsaicvbuild@gmail.com.",
    privacyOwnershipTitle: "6. Data Ownership",
    privacyOwnershipDesc: "You retain full ownership of all data and information you enter into the application. We do not claim any rights over your personal content.",
    privacyNoSharingTitle: "7. No Third-Party Sharing",
    privacyNoSharingDesc: "We never sell, rent, or share your personal information with third parties for marketing or any other purposes.",
    privacyLocalStorageTitle: "8. Local-First Storage",
    privacyLocalStorageDesc: "Our application is designed with a local-first approach. Your resume data is stored directly in your browser's local storage and never leaves your device unless you choose to export it.",
    privacyEncryptionTitle: "9. Data Encryption",
    privacyEncryptionDesc: "We use strong encryption to protect your data.",
    privacyAnalyticsTitle: "10. Anonymous Analytics",
    privacyAnalyticsDesc: "We may collect anonymous usage data to help us understand how users interact with the application and to improve our services. This data does not identify you personally.",
    privacyNoTrackingTitle: "11. No Cross-Site Tracking",
    privacyNoTrackingDesc: "We do not track your online activities across third-party websites or online services.",
    privacyRightToDeleteTitle: "12. Right to Erasure",
    privacyRightToDeleteDesc: "You have the right to delete all your data at any time. Since data is stored locally, clearing your browser's cache or local storage will permanently remove all your information.",
    privacyExternalLinksTitle: "14. External Links",
    privacyExternalLinksDesc: "Our application may contain links to other sites. We are not responsible for the privacy practices or content of such third-party websites.",
    privacyNoServerStorageTitle: "15. No Server-Side CV Storage",
    privacyNoServerStorageDesc: "We do not maintain copies of your generated CVs on our servers. Once you close your session, the only copy exists on your device.",
    termsOfUse: "Terms of Use",
    privacyPolicy: "Privacy Policy",
    languages: "Languages",
    projects: "Projects",
    awards: "Awards",
    publications: "Publications",
    volunteer: "Volunteer Work",
    references: "References",
    interests: "Interests",
    courses: "Courses",
    socialLinks: "Social Links",
    militaryService: "Military Service",
    drivingLicense: "Driving License",
    hobbies: "Hobbies",
    jobMatcher: "Job Description Matcher",
    jobMatcherDesc: "Paste the job description to see how well your resume matches.",
    analyzeMatch: "Analyze Match",
    matchScore: "Match Score",
    noKeywordsFound: "Paste a job description to begin analysis.",
    matchExcellent: "Excellent Match!",
    matchGood: "Good Match",
    matchFair: "Fair Match",
    matchPoor: "Poor Match",
    matchExcellentDesc: "Your resume is highly optimized for this role.",
    matchGoodDesc: "You have most of the required keywords.",
    matchFairDesc: "Consider adding more relevant keywords from the JD.",
    matchPoorDesc: "Your resume needs significant tailoring for this role.",
    getAiSuggestions: "Get AI Tailoring Suggestions",
    aiSuggestionsTitle: "AI Tailoring Suggestions",
    aiSuggestionsDesc: "Specific advice to make your resume a perfect match for this role.",
    aiOptimizing: "Analyzing with AI...",
    aiError: "Failed to get AI suggestions. Please try again.",
    recommended: "Recommended",
    aiToolbox: "AI Career Toolbox",
    aiToolboxDesc: "Powerful AI tools to help you land your dream job.",
    generateCoverLetter: "Generate Cover Letter",
    coverLetterTitle: "AI Cover Letter",
    coverLetterDesc: "A personalized cover letter tailored to this job.",
    generateInterviewQuestions: "Predict Interview Questions",
    interviewQuestionsTitle: "Predicted Interview Questions",
    interviewQuestionsDesc: "Questions you might be asked based on this JD.",
    analyzeSkillGap: "Analyze Skill Gap",
    skillGapTitle: "Skill Gap Analysis",
    skillGapDesc: "Skills you need to highlight or acquire.",
    optimizeBullets: "Optimize Bullet Points",
    generating: "Generating...",
    copyToClipboard: "Copy to Clipboard",
    copied: "Copied!",
    interviewCoach: "AI Interview Coach",
    interviewCoachDesc: "Practice for your interview with our AI coach. Get real-time feedback on your answers.",
    startInterview: "Start Mock Interview",
    endInterview: "End Session",
    typeAnswer: "Type your answer here...",
    send: "Send",
    coachGreeting: "Hello! I'm your AI Interview Coach. I'll ask you some common interview questions based on your resume and the job description you provided. Ready to start?",
    feedback: "Feedback",
    nextQuestion: "Next Question",
    loadingCoach: "Coach is thinking...",
    translateToArabic: "Translate to Arabic",
    translating: "Translating...",
    originalText: "Original (English)",
    translatedText: "Translated (Arabic)",
    starMethod: "STAR Method",
    starMethodDesc: "Use Situation, Task, Action, and Result to structure your answers.",
  },
  ar: {
    appName: "بناء السيرة الذاتية الذكي",
    edit: "تعديل",
    preview: "معاينة",
    exportPdf: "طباعة",
    downloadPdf: "تحميل PDF",
    fillSampleData: "تعبئة بيانات تجريبية",
    livePreview: "معاينة مباشرة",
    atsFormat: "تنسيق متوافق مع أنظمة ATS. استخدم 'حفظ كـ PDF' في نافذة الطباعة لأفضل النتائج.",
    autoSaving: "حفظ تلقائي",
    quickStats: "إحصائيات سريعة",
    totalResumes: "إجمالي السير الذاتية",
    atsScore: "نقاط ATS",
    jobTracker: "متتبع التقديمات",
    companyName: "اسم الشركة",
    jobStatus: "الحالة",
    appliedDate: "تاريخ التقديم",
    addJob: "إضافة وظيفة",
    statusApplied: "تم التقديم",
    statusInterview: "مقابلة",
    statusAccepted: "مقبول",
    statusRejected: "مرفوض",
    lastUpdated: "آخر تحديث",
    skillGapAnalysis: "تحليل فجوة المهارات",
    yourSkills: "مهاراتك",
    marketDemand: "طلب السوق",
    missingSkills: "أبرز المهارات المفقودة",
    aiCareerTips: "نصائح مهنية ذكية",
    tip1: "استخدم أفعالاً قوية مثل 'قدت'، 'طورت'، و 'حسنت'.",
    tip2: "اجعل إنجازاتك قابلة للقياس باستخدام الأرقام والنسب المئوية.",
    tip3: "تأكد من تحديث ملفك الشخصي على LinkedIn ومطابقته لسيرتك الذاتية.",
    tip4: "اجعل سيرتك الذاتية بين صفحة إلى صفحتين كحد أقصى لسهولة القراءة.",
    tip5: "تأكد من أن سيرتك الذاتية قابلة للقراءة آلياً بتجنب التصاميم المعقدة.",
    personalInfo: "المعلومات الشخصية",
    fullName: "الاسم الكامل",
    fullNamePlaceholder: "مثال: محمد أحمد",
    jobTitle: "المسمى الوظيفي المستهدف",
    jobTitlePlaceholder: "مثال: مهندس برمجيات",
    email: "البريد الإلكتروني",
    emailPlaceholder: "مثال: name@example.com",
    phone: "رقم الهاتف",
    phonePlaceholder: "مثال: 0501234567",
    location: "الموقع",
    locationPlaceholder: "مثال: الرياض، السعودية",
    linkedin: "لينكد إن",
    linkedinPlaceholder: "مثال: linkedin.com/in/username",
    summary: "الملخص المهني",
    summaryPlaceholder: "صف خلفيتك المهنية وأهم إنجازاتك باختصار...",
    experience: "الخبرة العملية",
    company: "الشركة",
    position: "المنصب",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    datePlaceholder: "MM/YYYY",
    present: "الحالي",
    expPlaceholder: "أهم الإنجازات (استخدم النقاط)...",
    education: "التعليم",
    school: "المدرسة / الجامعة",
    degree: "الدرجة العلمية",
    gradDate: "تاريخ التخرج",
    skills: "المهارات",
    skillsPlaceholder: "Build, TypeScript, Node.js...",
    technicalSoftSkills: "المهارات التقنية والشخصية",
    training: "التدريب / الدورات",
    certifications: "الشهادات",
    requiredField: "هذا الحقل مطلوب",
    validationError: "يرجى ملء جميع معلومات الاتصال المطلوبة (البريد الإلكتروني، الهاتف، العنوان، والمسمى الوظيفي).",
    settings: "الإعدادات",
    language: "اللغة",
    languageWarning: "ملاحظة: واجهة التطبيق بالعربية، ولكن يفضل كتابة معلومات السيرة الذاتية باللغة الإنجليزية لضمان أفضل توافق مع أنظمة ATS.",
    tipBanner: "نصيحة ATS: استخدم خطوطاً قياسية وتجنب التصاميم المعقدة. يضمن نظامنا أن تكون سيرتك الذاتية قابلة للقراءة آلياً.",
    tipQuantify: "نصيحة ATS: استخدم الأرقام! أضف نسباً مئوية وأرقاماً (مثال: 'زيادة المبيعات بنسبة 20%') للتميز.",
    tipTraining: "نصيحة ATS: أضف الدورات التدريبية التي تحتوي على كلمات مفتاحية مطابقة لوصف الوظيفة. اذكر المنصة (مثل Coursera أو Udemy).",
    tipCert: "نصيحة ATS: اكتب الاسم الكامل للشهادة متبوعاً بالاختصار بين قوسين (مثال: Project Management Professional (PMP)).",
    tipSummary: "نصيحة ATS: اجعل ملخصك موجزاً (3-5 جمل). ضمن أهم مسمياتك الوظيفية وأهم 2-3 مهارات.",
    tipExperience: "نصيحة ATS: استخدم النقاط لوصف مسؤولياتك. ابدأ كل نقطة بفعل قوي (مثال: 'قدت'، 'طورت').",
    targetJobDesc: "وصف الوظيفة المستهدفة",
    pasteJD: "الصق وصف الوظيفة هنا لتحسين التوافق مع ATS بنسبة 100%",
    jdPlaceholder: "الصق وصف الوظيفة التي تتقدم لها هنا...",
    basicContactInfo: "معلومات الاتصال الأساسية",
    careerOverview: "نظرة عامة موجزة عن مسارك المهني",
    historyAchievements: "تاريخك المهني وإنجازاتك",
    addExperience: "إضافة خبرة",
    academicQualifications: "مؤهلاتك الأكاديمية",
    addEducation: "إضافة تعليم",
    techSoftSkills: "المهارات التقنية والشخصية",
    trainingWorkshops: "الدورات التدريبية وورش العمل",
    addTraining: "إضافة تدريب",
    courseTitle: "عنوان الدورة",
    description: "الوصف",
    provider: "الجهة المقدمة",
    profAccreditedCerts: "الشهادات المهنية والمعتمدة",
    addCertification: "إضافة شهادة",
    certTitle: "عنوان الشهادة",
    issuingOrg: "الجهة المانحة",
    quantifyNumbers: "استخدم الأرقام للقياس",
    atsOptimizationTip: "نصيحة تحسين ATS",
    tipSkills: "نصيحة ATS: اذكر كلاً من المهارات التقنية (مثل 'Python') والمهارات الشخصية. تأكد من أن المهارات التي تدرجها تطابق المتطلبات المذكورة في وصف الوظيفة.",
    tipHeadings: "نصيحة ATS: استخدم عناوين أقسام قياسية مثل 'الخبرة' و'التعليم' لمساعدة النظام في تصنيف معلوماتك.",
    tipKeywords: "نصيحة ATS: استخدم الكلمات المفتاحية الموجودة في وصف الوظيفة لزيادة نسبة المطابقة.",
    tipContact: "نصيحة ATS: تأكد من أن رقم هاتفك وبريدك الإلكتروني نص عادي، وليس داخل صورة أو في رأس الصفحة.",
    tipNoTables: "نصيحة ATS: تجنب استخدام الجداول أو الأعمدة؛ التنسيق ذو العمود الواحد هو الأكثر أماناً لجميع أنظمة ATS.",
    tipBulletPoints: "نصيحة ATS: استخدم النقاط الدائرية القياسية. تجنب الرموز الفريدة التي قد لا تفهمها الأنظمة القديمة.",
    tipNoImages: "نصيحة ATS: لا تدرج صوراً شخصية أو أشرطة مهارات أو رسوماً بيانية. لا تستطيع أنظمة ATS قراءة البيانات داخل الصور.",
    tipJargon: "نصيحة ATS: استخدم الاسم الكامل متبوعاً بالاختصار بين قوسين، مثل 'Project Management Professional (PMP)'.",
    tipTailor: "نصيحة ATS: قم بتخصيص محتوى سيرتك الذاتية بناءً على كل وصف وظيفي تتقدم له لضمان أعلى نسبة مطابقة.",
    tipActionVerbs: "نصيحة ATS: ابدأ كل نقطة بفعل قوي مثل 'طورت'، 'قدت'، 'حققت'.",
    tipNoPronouns: "نصيحة ATS: لا تستخدم 'أنا' أو 'نحن' في سيرتك الذاتية. بدلاً من 'أنا قدت الفريق'، استخدم 'قدت فريقاً من 5 أشخاص'.",
    tipLinkedIn: "نصيحة ATS: تأكد من إضافة رابط ملفك الشخصي على LinkedIn. يميل مسؤولو التوظيف إلى التحقق من حضورك المهني عبر الإنترنت.",
    done: "تم",
    faq: "الأسئلة الشائعة",
    faqTitle: "الأسئلة الشائعة",
    faqLangTitle: "لماذا يجب أن أكتب بالإنجليزية؟",
    faqLangAnswer: "معظم الشركات العالمية وأنظمة ATS محسنة للغة الإنجليزية. الكتابة بالإنجليزية تزيد من فرصك في أن يتم تحليل بياناتك بشكل صحيح وجذب انتباه مسؤولي التوظيف الدوليين.",
    faqPdfTitle: "كيف أحفظ السيرة الذاتية بصيغة PDF؟",
    faqPdfAnswer: "اضغط على زر 'طباعة'. في نافذة الطباعة التي تظهر، اختر 'حفظ بتنسيق PDF' كوجهة. يضمن ذلك أفضل تنسيق وقابلية للقراءة آلياً.",
    faqFreeTitle: "هل الموقع مجاني؟",
    faqFreeAnswer: "نعم، الموقع مجاني بشكل كامل.",
    faqImagesTitle: "هل يمكنني استخدام الصور أو الأيقونات؟",
    faqImagesAnswer: "لا ننصح بذلك. غالباً ما تواجه أنظمة ATS صعوبة في قراءة الصور أو الأيقونات أو الرسومات المعقدة. يستخدم تطبيقنا تنسيقاً نصياً نظيفاً لضمان أقصى قدر من التوافق.",
    faqLengthTitle: "ما هو الطول المثالي للسيرة الذاتية؟",
    faqLengthAnswer: "بالنسبة لمعظم المهنيين، يفضل أن تكون بين صفحة إلى صفحتين. ركز على الجودة بدلاً من الكمية وتأكد من أن كل نقطة ذات صلة بالوظيفة التي تتقدم لها.",
    faqSecurityTitle: "هل بياناتي آمنة؟",
    faqSecurityAnswer: "نحن نلتزم بأعلى معايير الخصوصية ولا يتم مشاركة بياناتك مع جهة خارجية، بياناتك تستخدم فقط لإنشاء CV خاص بك.",
    faqAccountTitle: "هل أحتاج إلى إنشاء حساب؟",
    faqAccountAnswer: "لا، لا تحتاج إلى إنشاء حساب أو تسجيل دخول. يمكنك البدء في إنشاء سيرتك الذاتية فوراً، ويتم حفظ جميع بياناتك محلياً في متصفحك.",
    faqMobileTitle: "هل يمكنني استخدامه على الهاتف؟",
    faqMobileAnswer: "نعم، موقعنا متوافق تماماً مع جميع الأجهزة ويعمل بشكل مثالي على الهواتف الذكية والأجهزة اللوحية.",
    faqSupportTitle: "كيف يمكنني الحصول على الدعم؟",
    faqSupportAnswer: "يمكنك التواصل معنا عبر البريد الإلكتروني atsaicvbuild@gmail.com للرد عليك.",
    faqMultipleTitle: "هل يمكنني إنشاء أكثر من سيرة ذاتية؟",
    faqMultipleAnswer: "نعم، يمكنك إنشاء العدد الذي تحتاجه من السير الذاتية. يمكن تخصيص كل واحدة لوصف وظيفي محدد.",
    faqColorsTitle: "هل يمكنني استخدام الألوان في سيرتي الذاتية؟",
    faqColorsAnswer: "بينما الألوان الهادئة مقبولة، ننصح بالالتزام بتنسيق أبيض وأسود نظيف لضمان أقصى قدر من التوافق مع أنظمة ATS. يستخدم تطبيقنا تصميماً احترافياً عالي التباين وآمناً لجميع الأنظمة.",
    faqFontsTitle: "ما هي أفضل الخطوط لأنظمة ATS؟",
    faqFontsAnswer: "أفضل الخطوط هي الخطوط القياسية والنظيفة مثل Arial و Calibri و Helvetica. يستخدم تطبيقنا تلقائياً خطوطاً صديقة لأنظمة ATS لضمان تحليل سيرتك الذاتية بشكل صحيح.",
    faqGapsTitle: "كيف أتعامل مع الفجوات المهنية؟",
    faqGapsAnswer: "ركز على المهارات التي اكتسبتها خلال تلك الفترة، مثل العمل الحر أو الدورات التدريبية أو المشاريع الشخصية.",
    faqUploadTitle: "هل يمكنني رفع سيرتي الذاتية الحالية؟",
    faqUploadAnswer: "حالياً، تحتاج إلى إدخال معلوماتك يدوياً. يضمن ذلك تنظيم البيانات بشكل مثالي لأنظمة ATS.",
    faqPrintTitle: "ما هو أفضل متصفح للطباعة؟",
    faqPrintAnswer: "نوصي باستخدام Google Chrome أو Microsoft Edge. عند الطباعة، تأكد من إلغاء تحديد 'الرؤوس والتذييلات' وتحديد 'رسومات الخلفية' للحصول على أفضل نتيجة مرئية.",
    faqUpdateTitle: "كيف يمكنني تحديث سيرتي الذاتية لاحقاً؟",
    faqUpdateAnswer: "ببساطة عد إلى الموقع. بما أن بياناتك تُحفظ في التخزين المحلي لمتصفحك، ستجد معلوماتك بانتظارك لإجراء أي تحديثات.",
    faqSectionsTitle: "هل يمكنني إضافة أقسام أخرى؟",
    faqSectionsAnswer: "يركز نظامنا على الأقسام الأساسية المطلوبة لنجاح الـ ATS. ومع ذلك، يمكنك استخدام أقسام 'الخبرة' أو 'التدريب' لتضمين أنشطة مهنية أخرى ذات صلة.",
    faqSkillsTitle: "ما هي أفضل طريقة لسرد المهارات؟",
    faqSkillsAnswer: "قم بتصنيف مهاراتك حسب الفئة (مثل: لغات البرمجة، الأدوات، المهارات الشخصية) وتأكد من مطابقتها للكلمات المفتاحية في وصف الوظيفة.",
    faqBrowserTitle: "هل تُحفظ بياناتي إذا أغلقت المتصفح؟",
    faqBrowserAnswer: "نعم! نحن نستخدم التخزين المحلي لمتصفحك للحفاظ على تقدمك. طالما لم تقم بمسح بيانات المتصفح، ستكون سيرتك الذاتية متاحة عند عودتك.",
    faqAnyJobTitle: "هل يمكنني استخدام هذا لأي وظيفة؟",
    faqAnyJobAnswer: "نعم! تم تصميم أداتنا لمساعدتك في تخصيص سيرتك الذاتية لأي وصف وظيفي في مختلف المجالات.",
    faqFreshGradTitle: "ماذا لو كنت خريجاً جديداً؟",
    faqFreshGradAnswer: "ركز على تعليمك، والمشاريع الأكاديمية، والتدريب العملي، والمهارات ذات الصلة. أبرز إمكاناتك وكيف يتناسب خلفيتك الأكاديمية مع الدور الوظيفي.",
    faqPhotoTitle: "هل يجب أن أضع صورة شخصية؟",
    faqPhotoAnswer: "ننصح بعدم وضع صورة. العديد من أنظمة ATS لا تستطيع معالجة الصور، وفي العديد من المناطق، يُفضل عدم وضع صورة لتجنب التحيز غير الواعي في عملية التوظيف.",
    faqCvResumeTitle: "ما الفرق بين السيرة الذاتية (CV) والملخص المهني (Resume)؟",
    faqCvResumeAnswer: "عادة ما تكون السيرة الذاتية (CV) وثيقة مفصلة تغطي كامل مسيرتك المهنية والأكاديمية، بينما الملخص المهني (Resume) هو ملخص موجز مخصص لوظيفة معينة. يساعدك تطبيقنا في إنشاء ملخص مهني عالي التأثير.",
    faqReferencesTitle: "كيف يجب أن أتعامل مع المراجع؟",
    faqReferencesAnswer: "من الممارسات القياسية عدم وضع المراجع في سيرتك الذاتية. يمكنك تقديمها بشكل منفصل إذا طلبها صاحب العمل. هذا يوفر مساحة قيمة لإنجازاتك.",
    faqTemplateTitle: "هل يمكنني تغيير القالب؟",
    faqTemplateAnswer: "نحن نوفر تنسيقاً واحداً محسناً للغاية وصديقاً لأنظمة ATS. يضمن ذلك أن تكون سيرتك الذاتية دائماً احترافية وقابلة للقراءة آلياً، وهو أهم عامل للنجاح.",
    faqCertsTitle: "كيف أتعامل مع الشهادات؟",
    faqCertsAnswer: "اكتب الاسم الكامل للشهادة متبوعاً بالاختصار بين قوسين (مثال: Project Management Professional (PMP)). اذكر الجهة المانحة وتاريخ الحصول عليها.",
    faqAddressTitle: "هل يجب أن أضع عنواني الكامل؟",
    faqAddressAnswer: "في السير الذاتية الحديثة، يكفي ذكر المدينة والدولة فقط. العنوان التفصيلي لم يعد ضرورياً وقد يمثل مصدر قلق للخصوصية.",
    faqTechSkillsTitle: "ما هي أفضل طريقة لسرد المهارات التقنية؟",
    faqTechSkillsAnswer: "قم بتصنيفها حسب الفئة (مثل: لغات البرمجة، إطارات العمل، الأدوات). هذا يسهل على نظام الـ ATS ومسؤول التوظيف قراءة خبراتك.",
    faqSoftSkillsTitle: "كيف أتعامل مع المهارات الشخصية؟",
    faqSoftSkillsAnswer: "بدلاً من مجرد سردها، حاول إثباتها في قسم الخبرة. على سبيل المثال، بدلاً من قول 'لاعب فريق'، صف مشروعاً تعاونت فيه مع الآخرين لتحقيق هدف معين.",
    faqAcademicTitle: "هل يمكنني استخدامه للتقديم الأكاديمي؟",
    faqAcademicAnswer: "بينما نظامنا محسن للسير الذاتية المهنية، يمكنك استخدامه للأدوار الأكاديمية. ركز على أبحاثك ومنشوراتك وخبرتك التدريسية في الأقسام ذات الصلة.",
    faqFreelanceTitle: "كيف أتعامل مع العمل الحر؟",
    faqFreelanceAnswer: "عامله كأي وظيفة أخرى. اذكر 'عمل حر' كاسم للشركة وصف المشاريع التي عملت عليها والنتائج التي حققتها لعملائك.",
    contactTitle: "اتصل بنا",
    contactSub: "لديك سؤال؟ أرسل لنا رسالة وسنقوم بالرد عليك عبر البريد الإلكتروني في أقرب وقت.",
    contactName: "الاسم",
    contactEmail: "البريد الإلكتروني",
    contactSubject: "الموضوع",
    contactMessage: "الرسالة",
    contactSend: "إرسال الرسالة",
    contactSuccess: "تم إرسال الرسالة بنجاح!",
    contactSuccessSub: "سوف نقوم بالرد عليك عبر البريد الإلكتروني في أقرب وقت.",
    contactError: "فشل إرسال الرسالة. يرجى المحاولة مرة أخرى.",
    contactEmailLabel: "للتواصل: atsaicvbuild@gmail.com",
    contactSubjectOptions: [
      "استفسار عام",
      "دعم فني",
      "طلب ميزة جديدة",
      "الإبلاغ عن خطأ",
      "شراكة",
      "أخرى"
    ],
    adminTitle: "رسائل الإدارة",
    adminNoMessages: "لا توجد رسائل.",
    adminSecret: "كلمة سر الإدارة",
    adminLogin: "دخول",
    adminWrongSecret: "كلمة السر غير صحيحة. تم رفض الدخول.",
    adminReply: "الرد عبر البريد",
    adminDrafting: "جاري المسودة...",
    adminCopied: "تم النسخ!",
    adminCopy: "نسخ المسودة",
    adminDelete: "حذف الرسالة",
    adminMarkReplied: "تم الرد",
    adminReplied: "تم الرد عليها",
    adminConfirmDelete: "هل أنت متأكد من حذف هذه الرسالة؟",
    termsTitle: "شروط الاستخدام",
    termsAcceptance: "باستخدامك لموقع بناء السيرة الذاتية الذكي، فإنك توافق على هذه الشروط.",
    termsUsage: "الاستخدام: هذه الأداة مخصصة للاستخدام الشخصي لإنشاء السير الذاتية. أنت مسؤول عن المحتوى الذي تدخله.",
    termsPrivacy: "الخصوصية: يتم تخزين بياناتك محلياً في متصفحك. نحن لا نقوم بتخزين بيانات سيرتك الذاتية الشخصية على خوادمنا.",
    termsDisclaimer: "إخلاء المسؤولية: نحن لسنا مسؤولين عن أي نتائج توظيف أو أخطاء في المستندات الناتجة.",
    termsAts: "توافق ATS: بينما نوفر قالباً متوافقاً مع أنظمة ATS، فإن التوافق يعتمد على المحتوى الذي تقدمه. ننصح بالكتابة باللغة الإنجليزية للحصول على أفضل النتائج.",
    termsAcceptanceTitle: "1. قبول الشروط",
    termsAcceptanceDesc: "من خلال الوصول إلى واستخدام موقع بناء السيرة الذاتية الذكي، فإنك تقبل وتوافق على الالتزام بشروط وأحكام هذه الاتفاقية.",
    termsEligibilityTitle: "2. الأهلية",
    termsEligibilityDesc: "يجب أن يكون عمرك 13 عاماً على الأقل لاستخدام هذه الخدمة. باستخدامك للخدمة، فإنك تقر وتضمن استيفاءك لهذا الشرط.",
    termsLicenseTitle: "3. ترخيص الاستخدام",
    termsLicenseDesc: "نمنحك ترخيصاً شخصياً وغير حصري وغير قابل للتحويل لاستخدام البرنامج لإنشاء سيرتك الذاتية الشخصية.",
    termsProhibitedTitle: "4. الأنشطة المحظورة",
    termsProhibitedDesc: "أنت توافق على عدم استخدام الخدمة لأي غرض غير قانوني أو لحث الآخرين على أداء أو المشاركة في أي أعمال غير قانونية.",
    termsContentTitle: "5. مسؤولية محتوى المستخدم",
    termsContentDesc: "أنت المسؤول الوحيد عن دقة وقانونية المحتوى الذي تدخله في سيرتك الذاتية.",
    termsStorageTitle: "6. تخزين البيانات",
    termsStorageDesc: "يتم تخزين بياناتك محلياً في التخزين المحلي لمتصفحك. نحن لا نملك الوصول إلى بيانات سيرتك الذاتية الشخصية إلا إذا قمت بمشاركتها صراحة.",
    termsPrivacyTitle: "7. الخصوصية",
    termsPrivacyDesc: "نحن نقدر خصوصيتك. يرجى الرجوع إلى قسم سياسة الخصوصية للحصول على تفاصيل حول كيفية تعاملنا مع البيانات غير الشخصية.",
    termsAtsTitle: "9. أداء ATS",
    termsAtsDesc: "بينما قوالبنا محسنة لأنظمة ATS، لا يمكننا ضمان نجاح التحليل بنسبة 100% لكل نظام موجود.",
    termsAvailabilityTitle: "10. توفر النظام",
    termsAvailabilityDesc: "نحن نسعى جاهدين للحفاظ على توفر الخدمة على مدار الساعة طوال أيام الأسبوع ولكننا لا نضمن الوصول دون انقطاع بسبب الصيانة أو المشكلات الفنية.",
    termsIpTitle: "11. الملكية الفكرية",
    termsIpDesc: "البرمجيات والتصميم والعلامة التجارية هي ملكية فكرية لموقع بناء السيرة الذاتية الذكي.",
    termsThirdPartyTitle: "12. خدمات الطرف الثالث",
    termsThirdPartyDesc: "قد تحتوي خدمتنا على روابط لمواقع أو خدمات تابعة لأطراف ثالثة لا نملكها أو نسيطر عليها.",
    termsNoGuaranteeTitle: "13. لا ضمان للتوظيف",
    termsNoGuaranteeDesc: "استخدام هذه الأداة لا يضمن توظيفك أو حصولك على مقابلات عمل.",
    termsLiabilityTitle: "14. تحديد المسؤولية",
    termsLiabilityDesc: "لن نكون مسؤولين بأي حال من الأحوال عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية أو تأديبية.",
    termsIndemnityTitle: "15. التعويض",
    termsIndemnityDesc: "أنت توافق على تعويضنا وإبراء ذمتنا من أي مطالب أو خسائر أو مسؤوليات أو مطالبات أو نفقات يقدمها ضدنا أي طرف ثالث.",
    termsModificationsTitle: "17. التعديلات على الشروط",
    termsModificationsDesc: "نحن نحتفظ بالحق في تعديل هذه الشروط في أي وقت. استمرارك في استخدام الخدمة يشكل قبولاً للشروط الجديدة.",
    termsAccountsTitle: "8. حسابات المستخدمين (اختياري)",
    termsAccountsDesc: "إذا اخترت حفظ بياناتك، فأنت مسؤول عن الحفاظ على سرية جلستك المحلية وأي روابط مشاركة تقوم بإنشائها.",
    termsLawTitle: "16. القانون الواجب التطبيق",
    termsLawDesc: "تخضع هذه الشروط وتفسر وفقاً لقوانين الولاية القضائية التي تعمل فيها الخدمة، بغض النظر عن تضارب نصوص القوانين.",
    termsFeedbackTitle: "26. الملاحظات والاقتراحات",
    termsFeedbackDesc: "أي ملاحظات أو اقتراحات تقدمها تعتبر غير سرية ولنا الحق في استخدام هذه المعلومات على أساس غير مقيد.",
    termsAgreementTitle: "27. الاتفاقية الكاملة",
    termsAgreementDesc: "تشكل هذه الشروط الاتفاقية الكاملة بيننا فيما يتعلق بخدمتنا، وتحل محل أي اتفاقيات سابقة قد تكون بيننا فيما يتعلق بالخدمة.",
    termsContactTitle: "18. معلومات الاتصال",
    termsContactDesc: "إذا كان لديك أي أسئلة حول هذه الشروط، يرجى الاتصال بنا على atsaicvbuild@gmail.com.",
    termsConductTitle: "19. سلوك المستخدم",
    termsConductDesc: "أنت توافق على عدم استخدام الخدمة لإنشاء مستندات احتيالية، أو انتحال شخصية الآخرين، أو المشاركة في أي نشاط يعطل الخدمة.",
    termsTerminationTitle: "20. إنهاء الخدمة",
    termsTerminationDesc: "نحن نحتفظ بالحق في إنهاء أو تعليق الوصول إلى خدمتنا فوراً، دون إشعار مسبق، بسبب السلوك الذي نعتقد أنه ينتهك هذه الشروط أو يضر بالمستخدمين الآخرين.",
    termsCookiesTitle: "21. ملفات تعريف الارتباط والتخزين المحلي",
    termsCookiesDesc: "نحن نستخدم التخزين المحلي للمتصفح وملفات تعريف الارتباط الضرورية لحفظ بيانات سيرتك الذاتية وتفضيلاتك. باستخدامك للموقع، فإنك توافق على هذا التخزين.",
    termsUpdatesTitle: "22. تحديثات الخدمة",
    termsUpdatesDesc: "قد نقوم بتحديث أو تعديل أو إيقاف ميزات الخدمة في أي وقت لتحسين الأمان أو الأداء أو تجربة المستخدم.",
    termsNoWarrantyTitle: "23. لا توجد ضمانات",
    termsNoWarrantyDesc: "يتم تقديم الخدمة على أساس 'كما هي' و 'كما هي متوفرة' دون أي ضمانات من أي نوع، سواء كانت صريحة أو ضمنية.",
    termsDataAccuracyTitle: "24. دقة البيانات",
    termsDataAccuracyDesc: "أنت مسؤول عن ضمان أن جميع المعلومات المقدمة في سيرتك الذاتية دقيقة وصادقة.",
    termsSupportTitle: "25. سياسة الدعم",
    termsSupportDesc: "بينما نسعى جاهدين لتقديم الدعم عبر البريد الإلكتروني، فإننا لا نضمن وقتاً محدداً للرد على الاستفسارات.",
    privacyTitle: "سياسة الخصوصية",
    privacyIntro: "خصوصيتك تهمنا. توضح هذه السياسة كيفية تعاملنا مع بياناتك.",
    privacyDataCollectionTitle: "1. جمع البيانات",
    privacyDataCollectionDesc: "نحن لا نقوم بجمع أو تخزين بيانات سيرتك الذاتية الشخصية على خوادمنا. يتم تخزين جميع المعلومات التي تدخلها محلياً في متصفحك.",
    privacyCookiesTitle: "2. ملفات تعريف الارتباط والتخزين المحلي",
    privacyCookiesDesc: "نستخدم التخزين المحلي لحفظ تقدمك وملفات تعريف الارتباط الضرورية لوظائف الموقع وأمانه.",
    privacySecurityTitle: "3. أمن البيانات",
    privacySecurityDesc: "بينما تبقى بياناتك على جهازك، فإننا نطبق معايير أمان عالمية على خادمنا لحماية سلامة الخدمة.",
    privacyUpdatesTitle: "4. التغييرات على هذه السياسة",
    privacyUpdatesDesc: "قد نقوم بتحديث سياسة الخصوصية الخاصة بنا من وقت لآخر. سنقوم بإخطارك بأي تغييرات عن طريق نشر سياسة الخصوصية الجديدة على هذه الصفحة.",
    privacyContactTitle: "5. اتصل بنا",
    privacyContactDesc: "إذا كانت لديك أسئلة حول خصوصيتك، اتصل بنا على atsaicvbuild@gmail.com.",
    privacyOwnershipTitle: "6. ملكية البيانات",
    privacyOwnershipDesc: "أنت تحتفظ بالملكية الكاملة لجميع البيانات والمعلومات التي تدخلها في التطبيق. نحن لا ندعي أي حقوق على محتواك الشخصي.",
    privacyNoSharingTitle: "7. عدم المشاركة مع أطراف ثالثة",
    privacyNoSharingDesc: "نحن لا نبيع أو نؤجر أو نشارك معلوماتك الشخصية أبداً مع أطراف ثالثة لأغراض التسويق أو أي أغراض أخرى.",
    privacyLocalStorageTitle: "8. التخزين المحلي أولاً",
    privacyLocalStorageDesc: "تم تصميم تطبيقنا بنهج التخزين المحلي أولاً. يتم تخزين بيانات سيرتك الذاتية مباشرة في التخزين المحلي لمتصفحك ولا تغادر جهازك أبداً إلا إذا اخترت تصديرها.",
    privacyEncryptionTitle: "9. تشفير البيانات",
    privacyEncryptionDesc: "نستخدم تشفيراً قوياً لحماية بياناتك.",
    privacyAnalyticsTitle: "10. تحليلات مجهولة المصدر",
    privacyAnalyticsDesc: "قد نجمع بيانات استخدام مجهولة المصدر لمساعدتنا في فهم كيفية تفاعل المستخدمين مع التطبيق وتحسين خدماتنا. هذه البيانات لا تحدد هويتك الشخصية.",
    privacyNoTrackingTitle: "11. لا تتبع عبر المواقع",
    privacyNoTrackingDesc: "نحن لا نتتبع أنشطتك عبر الإنترنت عبر مواقع الطرف الثالث أو الخدمات عبر الإنترنت.",
    privacyRightToDeleteTitle: "12. الحق في الحذف",
    privacyRightToDeleteDesc: "لديك الحق في حذف جميع بياناتك في أي وقت. بما أن البيانات مخزنة محلياً، فإن مسح ذاكرة التخزين المؤقت للمتصفح أو التخزين المحلي سيؤدي إلى إزالة جميع معلوماتك بشكل دائم.",
    privacyExternalLinksTitle: "14. الروابط الخارجية",
    privacyExternalLinksDesc: "قد يحتوي تطبيقنا على روابط لمواقع أخرى. نحن لسنا مسؤولين عن ممارسات الخصوصية أو محتوى مواقع الطرف الثالث هذه.",
    privacyNoServerStorageTitle: "15. لا يوجد تخزين للسير الذاتية على الخادم",
    privacyNoServerStorageDesc: "نحن لا نحتفظ بنسخ من سيرك الذاتية التي تم إنشاؤها على خوادمنا. بمجرد إغلاق جلستك، توجد النسخة الوحيدة على جهازك.",
    termsOfUse: "شروط الاستخدام",
    privacyPolicy: "سياسة الخصوصية",
    languages: "اللغات",
    projects: "المشاريع",
    awards: "الجوائز",
    publications: "المنشورات",
    volunteer: "العمل التطوعي",
    references: "المراجع",
    interests: "الاهتمامات",
    courses: "الدورات التدريبية",
    socialLinks: "روابط التواصل الاجتماعي",
    militaryService: "الخدمة العسكرية",
    drivingLicense: "رخصة القيادة",
    hobbies: "الهوايات",
    jobMatcher: "محلل الوصف الوظيفي",
    jobMatcherDesc: "الصق وصف الوظيفة لمعرفة مدى مطابقة سيرتك الذاتية.",
    analyzeMatch: "تحليل المطابقة",
    matchScore: "نسبة المطابقة",
    noKeywordsFound: "الصق وصف الوظيفة للبدء بالتحليل.",
    matchExcellent: "مطابقة ممتازة!",
    matchGood: "مطابقة جيدة",
    matchFair: "مطابقة متوسطة",
    matchPoor: "مطابقة ضعيفة",
    matchExcellentDesc: "سيرتك الذاتية محسنة بشكل كبير لهذا الدور.",
    matchGoodDesc: "لديك معظم الكلمات المفتاحية المطلوبة.",
    matchFairDesc: "فكر في إضافة المزيد من الكلمات المفتاحية ذات الصلة من وصف الوظيفة.",
    matchPoorDesc: "سيرتك الذاتية تحتاج إلى تخصيص كبير لهذا الدور.",
    getAiSuggestions: "احصل على اقتراحات تخصيص بالذكاء الاصطناعي",
    aiSuggestionsTitle: "اقتراحات التخصيص بالذكاء الاصطناعي",
    aiSuggestionsDesc: "نصائح محددة لجعل سيرتك الذاتية مطابقة تماماً لهذا الدور.",
    aiOptimizing: "جاري التحليل بالذكاء الاصطناعي...",
    aiError: "فشل الحصول على اقتراحات الذكاء الاصطناعي. يرجى المحاولة مرة أخرى.",
    recommended: "الأفضل",
    aiToolbox: "صندوق أدوات المسار المهني الذكي",
    aiToolboxDesc: "صندوق أدوات المسار المهني الذكي لمساعدتك في الحصول على وظيفة أحلامك.",
    generateCoverLetter: "إنشاء خطاب التغطية",
    coverLetterTitle: "خطاب التغطية الذكي",
    coverLetterDesc: "خطاب تغطية مخصص ومصمم لهذه الوظيفة.",
    generateInterviewQuestions: "توقع أسئلة المقابلة",
    interviewQuestionsTitle: "أسئلة المقابلة المتوقعة",
    interviewQuestionsDesc: "الأسئلة التي قد تُطرح عليك بناءً على وصف الوظيفة.",
    analyzeSkillGap: "تحليل فجوة المهارات",
    skillGapTitle: "تحليل فجوة المهارات",
    skillGapDesc: "المهارات التي تحتاج إلى إبرازها أو اكتسابها.",
    optimizeBullets: "تحسين نقاط الخبرة",
    generating: "جاري الإنشاء...",
    copyToClipboard: "نسخ إلى الحافظة",
    copied: "تم النسخ!",
    interviewCoach: "مدرب المقابلات الذكي",
    interviewCoachDesc: "تدرب على مقابلتك مع مدربنا الذكي. احصل على ملاحظات فورية على إجاباتك.",
    startInterview: "بدء مقابلة تجريبية",
    endInterview: "إنهاء الجلسة",
    typeAnswer: "اكتب إجابتك هنا...",
    send: "إرسال",
    coachGreeting: "مرحباً! أنا مدرب المقابلات الذكي الخاص بك. سأطرح عليك بعض أسئلة المقابلة الشائعة بناءً على سيرتك الذاتية ووصف الوظيفة الذي قدمته. هل أنت مستعد للبدء؟",
    feedback: "ملاحظات",
    nextQuestion: "السؤال التالي",
    loadingCoach: "المدرب يفكر...",
    translateToArabic: "ترجمة للعربية",
    translating: "جاري الترجمة...",
    originalText: "النص الأصلي (إنجليزي)",
    translatedText: "النص المترجم (عربي)",
    starMethod: "STAR Method",
    starMethodDesc: "Use Situation, Task, Action, and Result to structure your answers.",
  },
};
